package com.jin.attendance_archive.res

object Strings {
    const val appName = "안디옥 출석체크"

    /** Common */
    const val dialogConfirm = "확인"
    const val dialogCancel = "취소"
    const val networkError = "네트워크 연결이 원활하지 못해 데이터를 불러올 수 없습니다\n네트워크 확인 후 다시 실행해주세요"

    /** Sign In */
    const val signInIdLabel = "아이디를 입력 후 로그인해주세요"
    const val signInIdPlaceHolder = "ID"
    const val signInConfirm = "로그인"
    const val signInIdEmpty = "아이디를 입력해주세요"
    const val signInIdWrong = "알맞은 아이디가 아닙니다\n확인 후 다시 시도해주세요"
    const val signInIdError = "연결이 원활하지 않습니다\n잠시 후 다시 시도해주세요"

    /** Sign Out */
    const val signOutMessage = "로그아웃 하시겠습니까?"
    const val signOutCompleted = "로그아웃하였습니다"

    /** Switch */
    const val switchOnMsg = "출석체크가 진행중입니다"
    const val switchOffMsg = "출석체크 진행중이 아닙니다"
    const val switchTitle = "출석체크 활성화"
    const val switchCompleted = "체크! 체크! 출석체크!"
    const val switchConfirm = "닫기"

    /** Attendance Type List */
    const val attendanceNotToDo = "출석체크 할 항목이 없습니다"
    const val attendanceProgress = "진행상황"

    /** Check List */
    const val checkStatusDone = "완료"
    const val checkStatusNotYet = "아직안함"

    /** Check **/
    const val attendanceCheckType0 = "결석"
    const val attendanceCheckType1 = "출석"
    const val attendanceCheckType2 = "헌신"
    const val attendanceReason = "결석사유"
    const val attendanceDoError = "잠시 후 다시 시도해주세요"
    const val attendanceDoCompleted = "출석체크를 완료했습니다"

    /** Check Fruit **/
    const val hasFruitAttendance = "출석"
    const val hasFruitFruit = "열매"
    const val hasFruitBelieve = "영접"
    const val hasFruitMeet = "말씀운동"
    const val hasFruitAddAttendance = "출석 추가하기"
    const val hasFruitAddDedication = "헌신 추가하기"
    const val hasFruitAddFruit1 = "영접자 추가하기"
    const val hasFruitAddFruit2 = "말씀운동 추가하기"
    const val hasFruitEditFruit1 = "영접자 수정하기"
    const val hasFruitEditFruit2 = "말씀운동 수정하기"
    const val hasFruitAdd = "추가 완료하기"
    const val hasFruitEdit = "수정 완료하기"
    const val hasFruitDelete = "삭제하기"
    const val hasFruitAttendanceDeleteMsg = "출석 명단에서 제외하시겠습니까?"
    const val hasFruitAttendanceDeleteCompleted = "출석 명단에서 제외하였습니다"
    const val hasFruitDedicationDeleteMsg = "헌신 명단에서 제외하시겠습니까?"
    const val hasFruitDedicationDeleteCompleted = "헌신 명단에서 제외하였습니다"
    const val hasFruitDeleteMsg = "작성된 열매를 삭제하시겠습니까?"
    const val hasFruitDeleteCompleted = "작성된 열매를 삭제했습니다"
    const val hasFruitDedication = "헌신사유"
    const val hasFruitPreacher = "전도자"
    const val hasFruitBeliever = "영접자"
    const val hasFruitTeacher = "사역자"
    const val hasFruitAge = "나이"
    const val hasFruitPhone = "전화번호"
    const val hasFruitRemeet = "재만남"
    const val hasFruitFrequency = "만난 횟수"
    const val hasFruitPlace = "만난 장소"
    const val hasFruitDedicationEmpty = "헌신 사유를 입력해주세요"
    const val hasFruitPreacherEmpty = "전도자를 입력해주세요"
    const val hasFruitBelieverEmpty = "영접자를 입력해주세요"
    const val hasFruitPeopleDuplicated = "해당 명단이 새로운 출석 상태로 변경되었습니다"
    const val hasFruitDuplicated = "전도자와 영접자가 같은 열매가 이미 작성되어 있습니다"

    /** SearchPeople **/
    const val searchPeopleLabel = "이름을 입력하세요"
    const val searchPeoplePlaceHolder = "이름"

    /** Management */
    const val managementScreen = "관리자 페이지"
    const val managementFilingWeeklyTitle = "주간 출석 파일 만들기"
    const val managementFilingWeeklyGuide = "한 주간 기록한 출석 결과를 모아서 하나의 엑셀 파일로 만들 수 있습니다"
    const val managementFilingYearlyTitle = "연간 출석 파일 만들기"
    const val managementFilingYearlyGuide = "1년간 기록한 출석 결과를 엑셀 파일로 만들 수 있습니다"
    const val managementFilingFruitTitle = "현장전도 출석/열매 파일 만들기"
    const val managementFilingFruitGuide = "현장전도 출석과 열매 결과를 엑셀 파일로 만들 수 있습니다"
    const val managementPeopleTitle = "출석명단 관리"
    const val managementPeopleGuide = "출석명단을 추가, 삭제, 이동할 수 있습니다"
    const val managementUserTitle = "사용자 관리"
    const val managementUserGuide = "앱의 모든 사용자 정보를 확인할 수 있습니다"
    const val managementLogTitle = "로그"
    const val managementLogGuide = "로그를 볼 수 있습니다"

    /** Filing */
    const val filingWeeklyGuide = "파일로 생성할 출석의 주간을 선택하세요"
    const val filingYearGuide = "파일로 생성할 출석의 년도를 선택하세요"
    const val filingSelectionGuide = "파일로 생성할 출석의 종류를 선택하세요"
    const val filingSun = "주일예배 전체"
    const val filingFruitWeekly = "선택한 주의 출석과 열매를 파일로 만듭니다"
    const val filingFruitMonthly = "한 달간의 출석을 파일로 만듭니다"
    const val filingFruitYearly = "1년 전체의 출석을 파일로 만듭니다"
    const val filingGenerateFile = "파일 생성하기"
    const val filingDownload = "파일 다운로드하기"
    const val filingShareViaKakaoTalk = "카카오톡으로 전송하기"
    const val filingShareViaEmail = "이메일로 전송하기"
    const val filingGenerateMsg = "파일이 생성되었습니다"
    const val filingGenerateFailureMsg = "파일 생성에 실패하였습니다"
    const val filingNoKakaoTalkMsg = "카카오톡이 설치되어 있지 않습니다"
    const val filingChooserTitleToOpen = "파일을 열기 위한 앱을 선택하세요"
    const val filingChooserTitleToSend = "파일을 전송하기 위한 앱을 선택하세요"
    const val filingNoFileMsg = "생성된 파일이 없거나 열 수 없는 파일입니다"
    const val filingRegenerateMsg = "다시 파일을 만드시면 전에 생성된 파일은 저장되지 않습니다\n파일을 새로 생성하시겠습니까?"

    /** Manage People */
    const val managePeopleGuide = "출석명단을 추가, 수정할 수 있습니다"
    const val managePeopleActivated = "활성화"
    const val managePeopleInactivated = "비활성화"
    const val managePeopleTitleCreate = "출석명단 추가"
    const val managePeopleTitleEdit = "출석명단 수정"
    const val managePeopleOrgTitleCreate = "소속 추가"
    const val managePeopleOrgTitleEdit = "소속 수정"
    const val managePeopleOrgConfirm = "소속 작성 완료"
    const val managePeopleOrgDuplicated = "이미 소속되어 있습니다"
    const val managePeopleNameEmpty = "이름을 입력해주세요"
    const val managePeopleDutyEmpty = "직분을 선택해주세요"
    const val managePeopleCreateMsg = "해당 출석명단을 추가하시겠습니까?"
    const val managePeopleEditMsg = "해당 출석명단을 수정하시겠습니까?"
    const val managePeopleCreateCompleted = "출석명단을 추가하였습니다"
    const val managePeopleEditCompleted = "출석명단을 수정하였습니다"
    const val managePeopleCreateFailure = "출석명단을 추가하지 못했습니다\n잠시 후 다시 시도해주세요"
    const val managePeopleEditFailure = "출석명단을 수정하지 못했습니다\n잠시 후 다시 시도해주세요"
    const val managePeopleSameNameFailure = "동일한 이름이 있습니다\n이름을 중복되지 않게 변경해주세요"
    const val managePeopleSubtitle1 = "1. 이름"
    const val managePeopleSubtitle2 = "2. 직분"
    const val managePeopleSubtitle3 = "3. 소속(결과 취합 파일에서는 첫 번째 소속에 명단이 기록됩니다)"
    const val managePeopleSubtitle3Guide = "소속을 누르시면 첫 번째 순서로 변경됩니다"
    const val managePeopleSubtitle4 = "4. 활성화/비활성화"
    const val managePeopleOrgCreate = "추가하기"
    const val managePeopleOrgDeleteMsg = "해당 소속을 삭제하시겠습니까?"
    const val managePeopleOrgDeleteCompleted = "해당 소속을 삭제하였습니다"
    const val managePeopleOrgSubtitle1 = "1. 구미/서울"
    const val managePeopleOrgSubtitle2 = "2. 카테고리1"
    const val managePeopleOrgSubtitle3 = "3. 카테고리2"
    const val managePeopleOrgSubtitle4 = "4. 카테고리3"
    const val managePeopleOrgCustom = "직접입력"
}